### ISSUE TITLE
Implement and Test Nav2 stack on ergoCubSN000

### ISSUE THREAD

**Issue by SimoneMic** [hsp-iit/project-ergocub#111]
Things to test:

- [x] Costmaps and depth obstacle detection
- [ ] Dummy Planner (really low priority)
- [ ] Dummy plan tracker (really low priority)
- [x] Nav2 planners tests
- [x] Keepout Zones in costmaps

**Comment by vigisushrutha23** [comment]
I think we can close this issue as we Don't have this robot any more.
