### ISSUE TITLE
Complete Integration of Nav-Stack+Bimanual+Walking 

### ISSUE THREAD

**Issue by vigisushrutha23** [hsp-iit/project-ergocub#125]
This is the final demo of the full integration of EVERYTHING.

- [ ] Combine Navigation and get RVIZ outputs while Nav commands for walking target goal are sent + manual Bimanual commands are sent.
- [ ] Combine autonomous object manipulation with Nav+walking+Bimanual and perform experiment behind the desk in robot arena.
- [ ] Perform experiment in a suitable arena to show full object manipulation and robot sidestepping capabilities in appropriate location.

**Comment by vigisushrutha23** [comment]
Finished integrating the nav stack in simulation to run with minimal slowdown using an older version of Simone's Docker on the simulation designed for paper. We used an older version of the navigation stack luanch in the docker, not the one on the robot. We had to shift a fork but that can be merged later with the original walking controller to have a separate param file for navigation params if needed.

![image](https://github.com/hsp-iit/project-ergocub/assets/5215434/034315fd-8888-48d3-b0a3-f5f14850503d)

**Comment by mebbaid** [comment]
Today I verified that we can get more torso motion during walking when the bi-manual manipulation commands are active. The trick is to play with those weights and increase them a bit https://github.com/robotology/walking-controllers/blob/945b36f487a44f1c5e11d0250c886bfcecbc3a4e/src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/iFeel_joint_retargeting/tasks/retargeting.ini#L33C1-L33C24

One other thing that I need to see the effect of before closing that point would be to study the effect of reducing those weights https://github.com/robotology/walking-controllers/blob/945b36f487a44f1c5e11d0250c886bfcecbc3a4e/src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/iFeel_joint_retargeting/tasks/torso.ini#L16

**Comment by vigisushrutha23** [comment]
> Today I verified that we can get more torso motion during walking when the bi-manual manipulation commands are active. The trick is to play with those weights and increase them a bit https://github.com/robotology/walking-controllers/blob/945b36f487a44f1c5e11d0250c886bfcecbc3a4e/src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/iFeel_joint_retargeting/tasks/retargeting.ini#L33C1-L33C24
> 
> One other thing that I need to see the effect of before closing that point would be to study the effect of reducing those weights https://github.com/robotology/walking-controllers/blob/945b36f487a44f1c5e11d0250c886bfcecbc3a4e/src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/iFeel_joint_retargeting/tasks/torso.ini#L16

Can we try to test this on the ergoCubSN000 in the upcoming days or is this still something that requires more testing in simulation?

**Comment by vigisushrutha23** [comment]
Closing this issue as most of it is completed and old as well
