### ISSUE TITLE
Evaluate the use of native `realsense-ros` pkg for camera instead of YARP device

### ISSUE THREAD

**Issue by SimoneMic** [hsp-iit/project-ergocub#127]
The [official ros2 package](https://github.com/IntelRealSense/realsense-ros) from Intel for the D4xx Realsense offers native filtering techniques and features that could improve the use of the camera and its depth.

I plan on testing this package by installing it in `ergocub-head`, and launching it directly from there, bypassing the YARP devices and yarprobotinterface. 
The only downside, and potential issue, is the bandwith occupation of the data stream. However, the filtering should minimize this issue.

**Comment by vigisushrutha23** [comment]
https://github.com/ros-perception/image_transport_plugins/tree/humble 

The above is the package to do compressed depth image transport which can be used to publish compressed images on the head.

**Comment by SimoneMic** [comment]
https://github.com/IntelRealSense/librealsense/blob/master/doc/post-processing-filters.md
Filters available

**Comment by SimoneMic** [comment]
Implemented them on https://github.com/robotology/yarp-device-realsense2/pull/46
