### ISSUE TITLE
Test & Standardize BT and Perception modules with new manipulation code

### ISSUE THREAD

**Issue by Woolfrey** [hsp-iit/project-ergocub#133]
An [improved repository](https://github.com/Woolfrey/ergocub-bimanual) exists for the control of the upper-body of the ergoCub. We need to test its integration with the BT and perception, then standardize the associated config files.

- [x] List of joint names are in the correct order (must match AMI's walking controller)
- [ ] Control parameters for Cartesian control & redundant task satisfactory
- [ ] List of actions for joint control and Cartesian control are set

We should test this in Gazebo before proceeding to test the code on the new ergoCub 1.2.

**Comment by steb6** [comment]
@andrearosasco, @Woolfrey and me just tested the latest ergocub-bimanual code and it works! See #14
The order of the joints is the following:  
```
joint_names (torso_pitch   torso_roll   torso_yaw \
             l_shoulder_pitch   l_shoulder_roll   l_shoulder_yaw   l_elbow   l_wrist_roll   l_wrist_pitch   l_wrist_yaw \
             r_shoulder_pitch   r_shoulder_roll   r_shoulder_yaw   r_elbow   r_wrist_roll   r_wrist_pitch   r_wrist_yaw)
```
