### ISSUE TITLE
Benchmark Action Recognition

### ISSUE THREAD

**Issue by Woolfrey** [hsp-iit/project-ergocub#142]
We need to tune the action recognition so that it:
1. Reliably detects the correct action.
2. Doesn't execute the wrong action, and
3. Work on people with different proportions.

**Comment by steb6** [comment]
@lornat75 @Woolfrey 
@andrearosasco and me just finished to install and test the ICRA23 demo for the open day of the 20th December on ergoCubSN001.
Everything works fine as shown in the video below.

https://github.com/hsp-iit/project-ergocub/assets/24273206/e9a0f2cc-2826-41cc-beb7-a4ba45c20e7b

The installation took about 3 hours, where we needed to:
- build the docker image of the perception pipeline
- build the TensorRT engines (concurrently)
- install all the applications (pose-streamer, gaze-controller, manipulation, ...)
- create the .xml file to start all the applications easily from the yarpmanager (stored in ergocublap001 in $ROBOT_CODE/hsp) as shown below

![Screenshot 2023-12-05 163417](https://github.com/hsp-iit/project-ergocub/assets/24273206/e5d6d8fd-7a81-4cdb-9221-8f6ecff80b70)

There are some improvements that can be made before the real demo:
- [ ] the gaze controller is not too smooth
- [ ] actions can be improved (better handshake and hello)
- [ ] the wrists are not working at the moment, icub-tech is working on it, but we have to consider that they could not work during the demo
- [ ] there is a visual bug in the human-console
- [ ] we need to make a new support set for the new robot to target the demo
- [ ] grasping poses does not seem too accurate

**Comment by steb6** [comment]
> Thanks @steb6 for the detailed report. I would add to the list also that depth compression should be enabled on the `ergcub-head` machine

@xEnVrE absolutely! I was considering it a necessary step :)

**Comment by steb6** [comment]
> Nice work @steb6 and @andrearosasco. Can we consider this closed now?
> 
> Perhaps we should put the "improvements" in new issues?

Yes, I agree!
