### ISSUE TITLE
Overfit Box Detection

### ISSUE THREAD

**Issue by Woolfrey** [hsp-iit/project-ergocub#143]
We need to choose a standard object for the hand-over task and train the neural network to detect it reliably.

**Comment by andrearosasco** [comment]
If the usuale cardboard box is the object that we are gonna use, we can consider it done:

https://github.com/hsp-iit/project-ergocub/assets/47559809/5c6352e8-cea7-4107-acfd-8f65a8a934ba

To move to other object I'm considering this method:

https://github.com/hsp-iit/project-ergocub/assets/47559809/b3cc8b45-9a85-4343-b7f3-496414e44a26

for which I developed a GUI and that can detect objects specified with text. But it will need time and testing
