### ISSUE TITLE
Process Data From Vicon, Obtain Plots and Videos With ErgocubSN001

### ISSUE THREAD

**Issue by vigisushrutha23** [hsp-iit/project-ergocub#167]
This issue is to discuss the processing of data from the vicon and getting videos and frames to be put in the paper in the results section

**Comment by vigisushrutha23** [comment]
After a lot of corrections, fixes and trial and error, on March 5th, @mebbaid, @SimoneMic  and I performed walking+bimanual integration experiments and were able to observe the performance needed. Raw X-Y plot is somewhat chaotic and could potentially cause misunderstandings without additional content. To that effect. I have created a very rough and snappy animation of the marker trajectories using matlab as can be seen below. 

https://github.com/hsp-iit/project-ergocub/assets/5215434/a11a7e6c-1250-46d9-bdf2-34f6aa976f08

Can this be potentially used in the paper?

**Comment by vigisushrutha23** [comment]
For the experiment involving rotating the object, we didn't observe much space gain as can be seen in the  animation video below. We will attempt to get the data by adding a translation to the orientation change.


https://github.com/hsp-iit/project-ergocub/assets/5215434/55bc5db6-5e8f-41ea-a48f-ecc362f24bfb

**Comment by vigisushrutha23** [comment]
Further to the above posts we obtained videos with rotation+translation actions. The marker tracking is as follows.

https://github.com/hsp-iit/project-ergocub/assets/5215434/4c8e236f-d71d-4dc4-8964-f55e57a835a5

I further add videos from the final experiment involving path shift. 

https://github.com/hsp-iit/project-ergocub/assets/5215434/9bc4b41f-9e94-4d1f-ab77-bd634fde21a1

**Comment by vigisushrutha23** [comment]
The experiment videos for the (ROT+TRANS) Object action. 

https://github.com/hsp-iit/project-ergocub/assets/5215434/186a634d-ec84-4187-b1ac-c121d1475416


The experiment video that shows the path shift with the (ROT+TRANS) object action

https://github.com/hsp-iit/project-ergocub/assets/5215434/0eebe5de-75e9-429b-b35a-af510ec1470d

**Comment by mebbaid** [comment]
### Experiments diary 15 March
- We needed to fidle with the minimum turning radius on the navigation side
- we need to restore the number of steps before the shift in the navigation side

We managed to get a nice video. Also supporting videos from Jabra and the screencast are here
 `screen cast of RViz navigation interface`
[Screencast from 03-15-2024 09:58:46 AM.webm](https://github.com/hsp-iit/project-ergocub/assets/36491318/6f7824c0-191f-48b1-bb91-0817049022d8)

`jabra`
https://github.com/hsp-iit/project-ergocub/assets/36491318/d8163fc2-626f-4ca9-bf46-decfaec07b4c

**Comment by vigisushrutha23** [comment]
March 15 Video taken on my phone due to absence of cameras. I am not sure of the quality on the big screen now.
https://github.com/hsp-iit/project-ergocub/assets/5215434/96ac1d76-7565-4e64-83d7-c828cbb5928e

**Comment by vigisushrutha23** [comment]
Initial Draft of IROS Submission Video.

https://github.com/hsp-iit/project-ergocub/assets/5215434/a8e56267-d087-4308-b552-6619f10a3df4

**Comment by Woolfrey** [comment]
@vigisushrutha23, here are my suggestions.

I think it's best to have minimal text because it's a short video and people won't have time to read everything.

At 00:04s:
```
Objective: Avoid oncoming human in a narrow corridor

How? Shift object pose and/or robot.

Architecture:
  Bimanual manipulation
+ Adapted navigation
+ Whole-body control
```
I'd also take out the flow chart because it's too much information in a short time.

At 00:08s:
```
Key Modules:

Bimanual manipulation:
- Solve for object pose (not hands)
- Pfaffain constraint maintains grasp

Adapted Navigation Stack
- Global path plan from smac2dplanner
- Re-sampled to generate robot footsteps

Whole-body Controller
- Stack-of-tasks QP
- (something else??)
```

**Comment by vigisushrutha23** [comment]
> @vigisushrutha23, here are my suggestions.
> 
> I think it's best to have minimal text because it's a short video and people won't have time to read everything.
> 
> At 00:04s:
> 
> ```
> Objective: Avoid oncoming human in a narrow corridor
> 
> How? Shift object pose and/or robot.
> 
> Architecture:
>   Bimanual manipulation
> + Adapted navigation
> + Whole-body control
> ```
> 
> I'd also take out the flow chart because it's too much information in a short time.
> 
> At 00:08s:
> 
> ```
> Key Modules:
> 
> Bimanual manipulation:
> - Solve for object pose (not hands)
> - Pfaffain constraint maintains grasp
> 
> Adapted Navigation Stack
> - Global path plan from smac2dplanner
> - Re-sampled to generate robot footsteps
> 
> Whole-body Controller
> - Stack-of-tasks QP
> - (something else??)
> ```

@Woolfrey  Awesome....thanks for the suggestions..you are right in that I have got full sentences in there....will shorten them as per your suggestions and upload another version in a bit.

**Comment by vigisushrutha23** [comment]
Uploading a newer draft after implementing @Woolfrey 's suggestions.

https://github.com/hsp-iit/project-ergocub/assets/5215434/02b64c1b-2876-49a9-b7d3-d2e3edebc01e

**Comment by Woolfrey** [comment]
@vigisushrutha23, do you have the original video of the basic actions for bimanual manipulation?

**Comment by mebbaid** [comment]
great @vigisushrutha23! Just noticed a typo in the slide "key modules" in `strack of tasks`. Putting it here just to remember to correct it later.

**Comment by vigisushrutha23** [comment]
Marking this as complete after better data extraction and plotting were done for the ICRA 2024 submission.
